includes = []
packages = ["default", "kitty", "ghostty", "cmd", "resticprofile", "pipewire", "hyprland", "onedrive"]

[files]
"dotconfig/hypr/JonasArchPc-hyprland.conf"= "~/.config/hypr/hyprland.conf"

[variables]
waybar_output = ["DP-1","DP-2"]
waybar_include_battery = false
waybar_disk_path = "/home/jonas"

hypr_bg_path="/home/jonas/onedrive/Pictures/bg/aseag.jpg"
hypr_bg_lock_path="/home/jonas/onedrive/Pictures/bg/ente-komisch.jpg"
