includes = []
packages = ["default", "kitty", "ghostty", "cmd", "resticprofile", "pipewire", "hyprland", "onedriver", "dev", "mail", "niri"]

[files]
"dotconfig/hypr/JonasArchPc-hyprland.conf"= "~/.config/hypr/hyprland.conf"
"dotconfig/niri/JonasArchPc-config.kdl" = "~/.config/niri/config.kdl"

[variables]
waybar_output = ["DP-1","DP-2"]
waybar_include_battery = false
waybar_disk_path = "/home/jonas"
waybar_niri = true

# hypr_bg_path="/home/jonas/onedrive/Pictures/bg/aseag.jpg"
# hypr_bg_path="/home/jonas/onedrive/Pictures/bg/aseag.jpg"
#hypr_bg_lock_path="/home/jonas/Pictures/dark-green.jpg"
#hypr_bg_path="/home/jonas/Pictures/dark-green.jpg"
hypr_bg_lock_path="/home/jonas/Pictures/bg/the-two-walls.jpg"
hypr_bg_path="/home/jonas/Pictures/bg/the-two-walls.jpg"
