includes = []
packages = ["default", "kitty", "ghostty", "cmd", "pipewire", "hyprland", "onedriver", "lemurs", "dev", "kanata", "mail", "niri"]

[files]
"dotconfig/hypr/jonschlaptop-hyprland.conf"= "~/.config/hypr/hyprland.conf"
"dotconfig/niri/jonschlaptop-config.kdl" = "~/.config/niri/config.kdl"

[variables]
waybar_output = ["eDP-1"]
waybar_include_battery = true
waybar_disk_path = "/"
waybar_niri = true

hypr_bg_path="/home/jonas/onedrive/Pictures/bg/aseag.jpg"
hypr_bg_lock_path="/home/jonas/onedrive/Pictures/bg/ente-komisch.jpg"

# onedrive_skip_dir=[
# 	'Pictures'
# ]
